apiVersion: v1
kind: Secret
metadata:
  name: queueforge-secret
  namespace: queueforge
type: Opaque
stringData:
  DB_USER: queueforge
  DB_PASSWORD: queueforge123
  POSTGRES_DB: queueforge
  POSTGRES_USER: queueforge
  POSTGRES_PASSWORD: queueforge123
